const CartActionTypes = {
  TOOGLE_CART: 'TOOGLE_CART',
  ADD_ITEMS: 'ADD_ITEMS',
  REMOVE_ITEMS_FROM_CART: 'REMOVE_ITEMS_FROM_CART',
  REMOVE_QUANTITY: 'REMOVE_QUANTITY',
  CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;
